/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'imai' at '16/11/23 16:14' with Gradle 3.0
 *
 * @author imai, @date 16/11/23 16:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
